# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
